name: Publish Page
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install cli
        run: cargo install -f wasm-bindgen-cli && cargo install -f --git https://github.com/PrivateRookie/rtml.git cargo-rtml
      - name: Build
        run: cargo-rtml build
      - uses: peaceiris/actions-gh-pages@v3.7.3
        name: deploy
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/dist
