name: Publish Page
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install wasm-pack
        run: cargo install wasm-pack
      - name: Build
        run: wasm-pack build --target web --no-typescript && cargo run --bin index
      - name: rm .gitignore
        run: rm ./pkg/.gitignore
      - uses: peaceiris/actions-gh-pages@v3.7.3
        name: deploy
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pkg
